### ISSUE TITLE
无法使用在最新的打卡系统

### ISSUE THREAD

**Issue by zzz1999** [System233/time-helper#15]
推送内容：
系统异常：您当前打卡内容与现有模板不符，请重新打卡~(10006)
```js
Error: 系统异常：您当前打卡内容与现有模板不符，请重新打卡~(10006)
    at /root/time-helper/dist/src/helper.js:45:39
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Helper.submitData (/root/time-helper/dist/src/helper.js:81:22)
    at async Helper.run (/root/time-helper/dist/src/helper.js:124:9)
    at async Object.main (/root/time-helper/dist/tools/index.js:59:22)
```
系统异常：您当前打卡内容与现有模板不符，请重新打卡~(10006)
```js
Error: 系统异常：您当前打卡内容与现有模板不符，请重新打卡~(10006)
    at /root/time-helper/dist/src/helper.js:45:39
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Helper.submitData (/root/time-helper/dist/src/helper.js:81:22)
    at async Helper.run (/root/time-helper/dist/src/helper.js:124:9)
    at async Object.main (/root/time-helper/dist/tools/index.js:59:22)
```

**Comment by zzz1999** [comment]
打开表单需要填写的内容大改了

**Comment by System233** [comment]
手动打一下卡试试，更新一下表单内容

**Comment by System233** [comment]
默认是把上次的打卡内容下载下来送回去的，如果表单有变动的话数据就不匹配了，所以试试手动打卡一次

**Comment by Yehuw** [comment]
你好，如何获取目前已更新的表单内容，设置变量传入😶‍🌫️

**Comment by System233** [comment]
> 你好，如何获取目前已更新的表单内容，设置变量传入😶‍🌫️

像是出现了普遍问题的样子，手动打开软件打一次卡也还不行么？
翻了下代码，表单是通过模板构建的，学校修改表单应该不会影响运行，那么就只能是打卡接口更新了，但我现在打不了卡，学校已经不用这个了，抓不了包来测试。
