### ISSUE TITLE
本地获取验证码时，400错误

### ISSUE THREAD

**Issue by themanforfree** [System233/time-helper#8]
Request failed with status code 400
```js
Error: Request failed with status code 400
    at createError (/home/gy/workspace/time-helper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/gy/workspace/time-helper/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/gy/workspace/time-helper/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by System233** [comment]
刚刚试了下，没有遇到400错误。
400错误表示请求的内容有问题。可以检查下本地启动脚本里是不是有特殊字符（如中文符号），参数名称是否写错，必要参数是否已添加。

**Comment by themanforfree** [comment]
还是无法正常使用 
不过我参照你的项目
用python改写了我校的打卡脚本
感谢大佬

**Comment by System233** [comment]
> 还是无法正常使用
> 不过我参照你的项目
> 用python改写了我校的打卡脚本
> 感谢大佬

嗯，问题解决了就好
